.TH LIBCIPF 3 "June 12, 2025"
.SH NAME
libci \- Portable Network Graphics (CI) Reference Library 1.6.49

.SH SYNOPSIS
\fB#include "cipriv.h"\fP

.SH DESCRIPTION
As of libci version 1.5.1, this manual is no longer maintained.  The private
function prototypes, declared in private header files, should not be accessed
by applications.

.SH "SEE ALSO"
.BR "libci"(3)

.SH AUTHORS
Cosmin Truta, Glenn Randers-Pehrson
