# Sample makefile for rci-win / rci2-win / wci using MSVC and NMAKE.
# Greg Roelofs
# Last modified:  2 June 2007
#
#	The programs built by this makefile are described in the book,
#	"CI:  The Definitive Guide," by Greg Roelofs (O'Reilly and
#	Associates, 1999).  Go buy a copy, eh?  Well, OK, it's not
#	generally for sale anymore, but it's the thought that counts,
#	right?  (Hint:  http://www.libci.org/pub/ci/book/ )
#
# Invoke this makefile from a DOS prompt window via:
#
#	%devstudio%\vc\bin\vcvars32.bat
#	nmake -nologo -f Makefile.w32
#
# where %devstudio% is the installation directory for MSVC / DevStudio.  If
# you get "environment out of space" errors, create a desktop shortcut with
# "c:\windows\command.com /e:4096" as the program command line and set the
# working directory to this directory.  Then double-click to open the new
# DOS-prompt window with a bigger environment and retry the commands above.
#
# This makefile assumes libci and zlib have already been built or downloaded
# and are in subdirectories at the same level as the current subdirectory
# (as indicated by the CIPATH and ZPATH macros below).  Edit as appropriate.
#
# Note that the names of the dynamic and static libci and zlib libraries
# used below may change in later releases of the libraries.  This makefile
# builds statically linked executables, but that can be changed by uncom-
# menting the appropriate CILIB and ZLIB lines.

!include <ntwin32.mak>


# macros --------------------------------------------------------------------

CIPATH = ../libci
CIINC = -I$(CIPATH)
#CILIB = $(CIPATH)/cidll.lib
CILIB = $(CIPATH)/libci.lib

ZPATH = ../zlib
ZINC = -I$(ZPATH)
#ZLIB = $(ZPATH)/zlibdll.lib
ZLIB = $(ZPATH)/zlibstat.lib

WINLIBS = -defaultlib:user32.lib gdi32.lib
# ["real" apps may also need comctl32.lib, comdlg32.lib, winmm.lib, etc.]

INCS = $(CIINC) $(ZINC)
RLIBS = $(CILIB) $(ZLIB) $(WINLIBS)
WLIBS = $(CILIB) $(ZLIB)

CC = cl
LD = link
RM = del
CPPFLAGS = $(INCS)
CFLAGS = -nologo -O -W3 $(cvars)
# [note that -W3 is an MSVC-specific compilation flag ("all warnings on")]
# [see %devstudio%\vc\include\win32.mak for cvars macro definition]
O = .obj
E = .exe

RLDFLAGS = -nologo -subsystem:windows
WLDFLAGS = -nologo

RCI  = rci-win
RCI2 = rci2-win
WCI  = wci

ROBJS  = $(RCI)$(O) readci$(O)
ROBJS2 = $(RCI2)$(O) readci2$(O)
WOBJS  = $(WCI)$(O) writeci$(O)

EXES = $(RCI)$(E) $(RCI2)$(E) $(WCI)$(E)


# implicit make rules -------------------------------------------------------

.c$(O):
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $<


# dependencies --------------------------------------------------------------

all:  $(EXES)

$(RCI)$(E): $(ROBJS)
	$(LD) $(RLDFLAGS) -out:$@ $(ROBJS) $(RLIBS)

$(RCI2)$(E): $(ROBJS2)
	$(LD) $(RLDFLAGS) -out:$@ $(ROBJS2) $(RLIBS)

$(WCI)$(E): $(WOBJS)
	$(LD) $(WLDFLAGS) -out:$@ $(WOBJS) $(WLIBS)

$(RCI)$(O):	$(RCI).c readci.h
$(RCI2)$(O):	$(RCI2).c readci2.h
$(WCI)$(O):	$(WCI).c writeci.h

readci$(O):	readci.c readci.h
readci2$(O):	readci2.c readci2.h
writeci$(O):	writeci.c writeci.h


# maintenance ---------------------------------------------------------------

clean:
#	ideally we could just do this:
#	$(RM) $(EXES) $(ROBJS) $(ROBJS2) $(WOBJS)
#	...but the Windows "DEL" command is none too bright, so:
	$(RM) r*$(E)
	$(RM) w*$(E)
	$(RM) r*$(O)
	$(RM) w*$(O)
