# Sample makefile for rci-win / rci2-win / wci using mingw32-gcc and make.
# Greg Roelofs
# Last modified:  2 June 2007
#
#	The programs built by this makefile are described in the book,
#	"CI:  The Definitive Guide," by Greg Roelofs (O'Reilly and
#	Associates, 1999).  Go buy a copy, eh?  Well, OK, it's not
#	generally for sale anymore, but it's the thought that counts,
#	right?  (Hint:  http://www.libci.org/pub/ci/book/ )
#
# Invoke this makefile from a DOS-prompt window via:
#
#	make -f Makefile.mingw32
#
# This makefile assumes libci and zlib have already been built or downloaded
# and are in subdirectories at the same level as the current subdirectory
# (as indicated by the CIDIR and ZDIR macros below).  It makes no assumptions
# at all about the mingw32 installation tree (W32DIR).  Edit as appropriate.
#
# Note that the names of the dynamic and static libci and zlib libraries
# used below may change in later releases of the libraries.  This makefile
# builds both statically and dynamically linked executables by default.
# (You need only one set, but for testing it can be handy to have both.)


# macros --------------------------------------------------------------------

#CIDIR = ../..#		for libci-x.y.z/contrib/gregbook builds
CIDIR = ../libci-win32
CIINC = -I$(CIDIR)
CILIBd = $(CIDIR)/libci.dll.a	# dynamically linked
CILIBs = $(CIDIR)/libci.a		# statically linked, local libci

#ZDIR = ../../../zlib-win32#	for libci-x.y.z/contrib/gregbook builds
ZDIR = ../zlib-win32
ZINC = -I$(ZDIR)
ZLIBd = $(ZDIR)/libzdll.a
ZLIBs = $(ZDIR)/libz.a

# change this to be the path where mingw32 installs its stuff:
W32DIR =
#W32DIR = /usr/local/cross-tools/i386-mingw32msvc
W32INC = -I$(W32DIR)/include
W32LIB = $(W32DIR)/lib/libuser32.a $(W32DIR)/lib/libgdi32.a

CC = gcc
#CC = i386-mingw32msvc-gcc #	e.g., Linux -> Win32 cross-compilation
LD = $(CC)
RM = rm -f
CPPFLAGS = $(INCS)
CFLAGS = -O -Wall $(MINGW_CCFLAGS)
# [note that -Wall is a gcc-specific compilation flag ("most warnings on")]
# [-ansi, -pedantic and -W can also be used]
LDFLAGS = $(MINGW_LDFLAGS)
O = .o
E = .exe

INCS = $(CIINC) $(ZINC) $(W32INC)
RLIBSd = $(CILIBd) $(ZLIBd) $(W32LIB) -lm
RLIBSs = $(CILIBs) $(ZLIBs) $(W32LIB) -lm
WLIBSd = $(CILIBd) $(ZLIBd)
WLIBSs = $(CILIBs) $(ZLIBs)

RCI   = rci-win
RCI2  = rci2-win
WCI   = wci

ROBJSd  = $(RCI)$(O) readci.pic$(O)
ROBJS2d = $(RCI2)$(O) readci2.pic$(O)
WOBJSd  = $(WCI)$(O) writeci.pic$(O)

RCIs  = $(RCI)-static
RCI2s = $(RCI2)-static
WCIs  = $(WCI)-static

ROBJSs  = $(RCI)$(O) readci$(O)
ROBJS2s = $(RCI2)$(O) readci2$(O)
WOBJSs  = $(WCI)$(O) writeci$(O)

STATIC_EXES  = $(RCIs)$(E) $(RCI2s)$(E) $(WCIs)$(E)
DYNAMIC_EXES = $(RCI)$(E) $(RCI2)$(E) $(WCI)$(E)

EXES = $(STATIC_EXES) $(DYNAMIC_EXES)


# implicit make rules -------------------------------------------------------

.c$(O):
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $<

%.pic$(O): %.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -DCI_BUILD_DLL -o $@ $<


# dependencies --------------------------------------------------------------

all:  $(EXES)

$(RCIs)$(E): $(ROBJSs)
	$(LD) $(LDFLAGS) -o $@ $(ROBJSs) $(RLIBSs)

$(RCI)$(E): $(ROBJSd)
	$(LD) $(LDFLAGS) -o $@ $(ROBJSd) $(RLIBSd)

$(RCI2s)$(E): $(ROBJS2s)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS2s) $(RLIBSs)

$(RCI2)$(E): $(ROBJS2d)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS2d) $(RLIBSd)

$(WCIs)$(E): $(WOBJSs)
	$(LD) $(LDFLAGS) -o $@ $(WOBJSs) $(WLIBSs)

$(WCI)$(E): $(WOBJSd)
	$(LD) $(LDFLAGS) -o $@ $(WOBJSd) $(WLIBSd)

$(RCI)$(O):	$(RCI).c readci.h
$(RCI2)$(O):	$(RCI2).c readci2.h
$(WCI)$(O):	$(WCI).c writeci.h

readci$(O) readci.pic$(O):	readci.c readci.h
readci2$(O) readci2.pic$(O):	readci2.c readci2.h
writeci$(O) writeci.pic$(O):	writeci.c writeci.h


# maintenance ---------------------------------------------------------------

clean:
	$(RM) $(EXES)
	$(RM) $(ROBJSs) $(ROBJS2s) $(WOBJSs)
	$(RM) $(ROBJSd) $(ROBJS2d) $(WOBJSd)
