# Sample makefile for rci-x / rci2-x / wci using gcc and make.
# Greg Roelofs
# Last modified:  2 June 2007
#
#	The programs built by this makefile are described in the book,
#	"CI:  The Definitive Guide," by Greg Roelofs (O'Reilly and
#	Associates, 1999).  Go buy a copy, eh?  Well, OK, it's not
#	generally for sale anymore, but it's the thought that counts,
#	right?  (Hint:  http://www.libci.org/pub/ci/book/ )
#
# Invoke this makefile from a shell prompt in the usual way; for example:
#
#	make -f Makefile.unx
#
# This makefile assumes libci and zlib have already been built or downloaded
# and are installed in /usr/local/{include,lib} or as otherwise indicated by
# the CI* and Z* macros below.  Edit as appropriate--choose only ONE each of
# the CIINC, CILIBd, CILIBs, ZINC, ZLIBd and ZLIBs lines.
#
# This makefile builds both dynamically and statically linked executables
# (against libci and zlib, that is), but that can be changed by modifying
# the "EXES =" line.  (You need only one set, but for testing it can be handy
# to have both.)


# macros --------------------------------------------------------------------

#CIDIR = /usr/local/lib
#CIINC = -I/usr/local/include/libci16
#CILIBd = -L$(CIDIR) -lci16 # dynamically linked, installed libci
#CILIBs = $(CIDIR)/libci16.a # statically linked, installed libci
# or:
CIDIR = ../..#	this one is for libci-x.y.z/contrib/gregbook builds
#CIDIR = ../libci
CIINC = -I$(CIDIR)
CILIBd = -Wl,-rpath,$(CIDIR) -L$(CIDIR) -lci16	# dynamically linked
CILIBs = $(CIDIR)/libci.a		# statically linked, local libci

ZDIR = /usr/local/lib
#ZDIR = /usr/lib64
ZINC = -I/usr/local/include
ZLIBd = -L$(ZDIR) -lz			# dynamically linked against zlib
ZLIBs = $(ZDIR)/libz.a			# statically linked against zlib
# or:
#ZDIR = ../zlib
#ZINC = -I$(ZDIR)
#ZLIBd = -Wl,-rpath,$(ZDIR) -L$(ZDIR) -lz  # -rpath allows in-place testing
#ZLIBs = $(ZDIR)/libz.a

#XINC = -I/usr/include			# old-style, stock X distributions
#XLIB = -L/usr/lib/X11 -lX11		#  (including SGI IRIX)
#XINC = -I/usr/openwin/include		# Sun workstations (OpenWindows)
#XLIB = -L/usr/openwin/lib -lX11
XINC = -I/usr/X11R6/include		# new X distributions (X.org, etc.)
XLIB = -L/usr/X11R6/lib -lX11
#XLIB = -L/usr/X11R6/lib64 -lX11	# e.g., Red Hat on AMD64

INCS = $(CIINC) $(ZINC) $(XINC)
RLIBSd = $(CILIBd) $(ZLIBd) $(XLIB) -lm
RLIBSs = $(CILIBs) $(ZLIBs) $(XLIB) -lm
WLIBSd = $(CILIBd) $(ZLIBd) -lm
WLIBSs = $(CILIBs) $(ZLIBs) -lm

CC = gcc
LD = gcc
RM = rm -f
CPPFLAGS = $(INCS) -DFEATURE_LOOP
CFLAGS = -O -Wall
#CFLAGS = -O -W -Wall -Wextra -pedantic -ansi
# [note that -Wall is a gcc-specific compilation flag ("most warnings on")]
# [-ansi, -pedantic, -Wextra, and -W can also be used]
LDFLAGS =
O = .o
E =

RCI   = rci-x
RCI2  = rci2-x
WCI   = wci

RCIs  = $(RCI)-static
RCI2s = $(RCI2)-static
WCIs  = $(WCI)-static

ROBJS  = $(RCI)$(O) readci$(O)
ROBJS2 = $(RCI2)$(O) readci2$(O)
WOBJS  = $(WCI)$(O) writeci$(O)

STATIC_EXES  = $(RCIs)$(E) $(RCI2s)$(E) $(WCIs)$(E)
DYNAMIC_EXES = $(RCI)$(E) $(RCI2)$(E) $(WCI)$(E)

EXES = $(STATIC_EXES) $(DYNAMIC_EXES)


# implicit make rules -------------------------------------------------------

.c$(O):
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $<


# dependencies --------------------------------------------------------------

all:  $(EXES)

$(RCIs)$(E): $(ROBJS)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS) $(RLIBSs)

$(RCI)$(E): $(ROBJS)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS) $(RLIBSd)

$(RCI2s)$(E): $(ROBJS2)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS2) $(RLIBSs)

$(RCI2)$(E): $(ROBJS2)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS2) $(RLIBSd)

$(WCIs)$(E): $(WOBJS)
	$(LD) $(LDFLAGS) -o $@ $(WOBJS) $(WLIBSs)

$(WCI)$(E): $(WOBJS)
	$(LD) $(LDFLAGS) -o $@ $(WOBJS) $(WLIBSd)

$(RCI)$(O):	$(RCI).c readci.h
$(RCI2)$(O):	$(RCI2).c readci2.h
$(WCI)$(O):	$(WCI).c writeci.h

readci$(O):	readci.c readci.h
readci2$(O):	readci2.c readci2.h
writeci$(O):	writeci.c writeci.h


# maintenance ---------------------------------------------------------------

clean:
	$(RM) $(EXES) $(ROBJS) $(ROBJS2) $(WOBJS)
