# Sample makefile for rci-x / rci2-x / wci for SGI using cc and make.
# Greg Roelofs
# Last modified:  7 March 2002
#
#	The programs built by this makefile are described in the book,
#	"CI:  The Definitive Guide," by Greg Roelofs (O'Reilly and
#	Associates, 1999).  Go buy a copy, eh?  Buy some for friends
#	and family, too.  (Not that this is a blatant plug or anything.)
#
# Invoke this makefile from a shell prompt in the usual way; for example:
#
#	make -f Makefile.sgi
#
# This makefile assumes libci and zlib have already been built or downloaded
# and are both installed in /usr/local/{include,lib} (as indicated by the
# CI* and Z* macros below).  Edit as appropriate--choose only ONE each of
# the CIINC, CILIB, ZINC and ZLIB lines.
#
# This makefile builds dynamically linked executables (against libci and zlib,
# that is), but that can be changed by uncommenting the appropriate CILIB and
# ZLIB lines.


# macros --------------------------------------------------------------------

CIINC = -I/usr/local/include/libci16
CILIB = -L/usr/local/lib -lci16	  # dynamically linked against libci
#CILIB = /usr/local/lib/libci16.a # statically linked against libci
# or:
#CIINC = -I../..
#CILIB = -L../.. -lci
#CILIB = ../../libci.a

ZINC = -I/usr/local/include
ZLIB = -L/usr/local/lib -lz		# dynamically linked against zlib
#ZLIB = /usr/local/lib/libz.a		# statically linked against zlib
#ZINC = -I../zlib
#ZLIB = -L../zlib -lz
#ZLIB = ../../../zlib/libz.a

XINC = -I/usr/include/X11		# old-style, stock X distributions
XLIB = -L/usr/lib/X11 -lX11
#XINC = -I/usr/openwin/include    	# Sun workstations (OpenWindows)
#XLIB = -L/usr/openwin/lib -lX11
#XINC = -I/usr/X11R6/include		# new X distributions (XFree86, etc.)
#XLIB = -L/usr/X11R6/lib -lX11

INCS = $(CIINC) $(ZINC) $(XINC)
RLIBS = $(CILIB) $(ZLIB) $(XLIB) -lm
WLIBS = $(CILIB) $(ZLIB)

CC = cc
LD = cc
RM = rm -f
# ABI must be the same as that used to build libci.
ABI =
CPPFLAGS =
CFLAGS = $(ABI) -O -fullwarn $(INCS)
LDFLAGS = $(ABI)
O = .o
E =

RCI  = rci-x
RCI2 = rci2-x
WCI  = wci

ROBJS  = $(RCI)$(O) readci$(O)
ROBJS2 = $(RCI2)$(O) readci2$(O)
WOBJS  = $(WCI)$(O) writeci$(O)

EXES = $(RCI)$(E) $(RCI2)$(E) $(WCI)$(E)


# implicit make rules -------------------------------------------------------

.c$(O):
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $<


# dependencies --------------------------------------------------------------

all:  $(EXES)

$(RCI)$(E): $(ROBJS)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS) $(RLIBS)

$(RCI2)$(E): $(ROBJS2)
	$(LD) $(LDFLAGS) -o $@ $(ROBJS2) $(RLIBS)

$(WCI)$(E): $(WOBJS)
	$(LD) $(LDFLAGS) -o $@ $(WOBJS) $(WLIBS)

$(RCI)$(O):	$(RCI).c readci.h
$(RCI2)$(O):	$(RCI2).c readci2.h
$(WCI)$(O):	$(WCI).c writeci.h

readci$(O):	readci.c readci.h
readci2$(O):	readci2.c readci2.h
writeci$(O):	writeci.c writeci.h


# maintenance ---------------------------------------------------------------

clean:
	$(RM) $(EXES) $(ROBJS) $(ROBJS2) $(WOBJS)
