# Project:   libci

# Copyright (C) 2020 Cameron Cawley
# Copyright (C) 1997 Tom Tanner

# Toolflags:
CCflags = -c -depend !Depend -IC:,C:zlib -g -throwback  -DRISCOS  -fnah -wz
Linkflags = -aif -o $@
LibFileflags = -c -l -o $@

# Final targets:
@.libci-lib:   @.o.ci @.o.cierror @.o.cirio @.o.ciwio @.o.cimem \
	@.o.cipread @.o.ciset @.o.ciget @.o.ciread @.o.cirtran \
	@.o.cirutil @.o.citrans @.o.ciwrite @.o.ciwtran @.o.ciwutil
	LibFile $(LibFileflags) @.o.ci @.o.cierror @.o.cirio @.o.cirtran \
	@.o.cimem @.o.cipread @.o.ciset @.o.ciget @.o.ciread @.o.ciwio \
	@.o.cirutil @.o.citrans  @.o.ciwrite @.o.ciwtran @.o.ciwutil
@.mm-libci-lib:   @.mm.ci @.mm.cierror @.mm.cirio @.mm.ciwio @.mm.cimem \
	@.mm.cipread @.mm.ciset @.mm.ciget @.mm.ciread @.mm.cirtran \
	@.mm.cirutil @.mm.citrans @.mm.ciwrite @.mm.ciwtran @.mm.ciwutil
	LibFile $(LibFileflags) @.mm.ci @.mm.cierror @.mm.cirio \
	@.mm.ciwio @.mm.cimem @.mm.cipread @.mm.ciset @.mm.ciget \
	@.mm.ciread @.mm.cirtran @.mm.cirutil @.mm.citrans @.mm.ciwrite \
	@.mm.ciwtran @.mm.ciwutil


# User-editable dependencies:
Test: @.citest
	Run @.citest
	@Remove @.citest

#It would be nice if you could stop "make" listing from here on!
@.citest:   @.o.citest @.libci-lib C:o.Stubs C:zlib.o.zlib
	Link $(Linkflags) @.o.citest @.libci-lib C:o.Stubs C:zlib.o.zlib

.SUFFIXES: .o .mm .c

.c.mm:
	MemCheck.CC cc $(ccflags) -o $@ LibCi:$<
.c.o:
	cc $(ccflags) -o $@ $<

# See scripts.cilibconf/mak for how to generate this:
@.h.cilibconf: @.scripts.cilibconf/h/prebuilt
	Copy @.scripts.cilibconf/h/prebuilt $@ ~CF~V

# Static dependencies:
@.o.ci @.o.cierror @.o.cirio @.o.ciwio @.o.cimem \
@.o.cipread @.o.ciset @.o.ciget @.o.ciread @.o.cirtran \
@.o.cirutil @.o.citrans @.o.ciwrite @.o.ciwtran @.o.ciwutil \
@.o.citest: @.h.cilibconf


# Dynamic dependencies:
