# makefile for libci
# Copyright (C) 2015, 2018-2025 Cosmin Truta
# Copyright (C) 2002, 2006, 2014 Glenn Randers-Pehrson
# Copyright (C) 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

# Where the zlib library and include files are located
#ZLIBLIB=/usr/local/lib
#ZLIBINC=/usr/local/include
ZLIBLIB=../zlib
ZLIBINC=../zlib

CC = cc
CPP = $(CC) -E
LD = $(CC)
AR = ar
RANLIB = ranlib
MV_F = mv -f
RM_F = rm -f
AWK = awk

NOHWOPT = -DCI_ARM_NEON_OPT=0 -DCI_MIPS_MSA_OPT=0 \
          -DCI_POWERPC_VSX_OPT=0 -DCI_INTEL_SSE_OPT=0 \
          -DCI_RISCV_RVV_OPT=0
DFNFLAGS = # DFNFLAGS contains -D options to use in the libci build
DFA_EXTRA = # extra files that can be used to control configuration
CPPFLAGS = -I$(ZLIBINC) $(NOHWOPT) # -DCI_DEBUG=5
CFLAGS = -O # -g
ARFLAGS = rc
LDFLAGS = -L$(ZLIBLIB) # -g
LIBS = -lz -lm

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts/cilibconf.h.prebuilt

OBJS = ci.o cierror.o ciget.o cimem.o cipread.o \
       ciread.o cirio.o cirtran.o cirutil.o ciset.o \
       citrans.o ciwio.o ciwrite.o ciwtran.o ciwutil.o

.c.o:
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o $@ $*.c

all: libci.a citest

# The standard cilibconf.h exists as scripts/cilibconf.h.prebuilt,
# copy this if the following doesn't work.
cilibconf.h: cilibconf.dfn
	$(RM_F) $@ cilibconf.c cilibconf.out cilibconf.tmp
	echo '#include "cilibconf.dfn"' >cilibconf.c
	@echo "## If '$(CC) -E' fails, try /lib/cpp (e.g. CPP='/lib/cpp')" >&2
	$(CPP) $(DFNFLAGS) cilibconf.c >cilibconf.out
	$(AWK) -f scripts/dfn.awk out=cilibconf.tmp cilibconf.out >&2
	$(MV_F) cilibconf.tmp $@

cilibconf.dfn: scripts/cilibconf.dfa scripts/options.awk ciconf.h ciusr.dfa $(DFA_XTRA)
	$(RM_F) $@ cilibconf.pre cilibconf.tmp
	@echo "## Calling $(AWK) from scripts/cilibconf.mak" >&2
	@echo "## If 'awk' fails, try a better awk (e.g. AWK='nawk')" >&2
	$(AWK) -f scripts/options.awk out=cilibconf.pre\
	    version=search ciconf.h scripts/cilibconf.dfa\
	    ciusr.dfa $(DFA_XTRA) >&2
	$(AWK) -f scripts/options.awk out=cilibconf.tmp cilibconf.pre >&2
	$(MV_F) cilibconf.tmp $@

libci.a: $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)
	$(RANLIB) $@

citest: citest.o libci.a
	$(LD) $(LDFLAGS) -o $@ citest.o libci.a $(LIBS)

test: citest
	./citest

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false

clean:
	$(RM_F) *.o libci.a citest ciout.ci cilibconf.h
	$(RM_F) cilibconf.c cilibconf.dfn cilibconf.out cilibconf.pre

# DO NOT DELETE THIS LINE -- make depend depends on it.

ci.o:      ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cierror.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciget.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cimem.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cipread.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciread.o:  ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciset.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
citrans.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwrite.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h

citest.o:  ci.h ciconf.h cilibconf.h
