# makefile for libci
# Copyright (C) 2022-2025 Cosmin Truta
# Copyright (C) 2002, 2014 Glenn Randers-Pehrson
# Copyright (C) 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h
#
# Modified for LC56/ATARI assumes libz.lib is in same dir and uses default
# rules for library management
#
CPPFLAGS = -I../zlib
CFLAGS = -O
LBR = ci.lib
LDFLAGS = -L. -L../zlib -lci -lz -lm

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts/cilibconf.h.prebuilt

OBJS = $(LBR)(ci.o) $(LBR)(cierror.o) $(LBR)(ciget.o) $(LBR)(cimem.o) \
       $(LBR)(cipread.o) $(LBR)(ciread.o) $(LBR)(cirio.o) \
       $(LBR)(cirtran.o) $(LBR)(cirutil.o) $(LBR)(ciset.o) \
       $(LBR)(citrans.o) $(LBR)(ciwio.o) $(LBR)(ciwrite.o) \
       $(LBR)(ciwtran.o) $(LBR)(ciwutil.o)

all: $(LBR) citest.ttp

.c.o:
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c

$(LBR): $(OBJS)

$(OBJS): cipriv.h ci.h ciconf.h cilibconf.h ciinfo.h cistruct.h cidebug.h

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	cp $(CILIBCONF_H_PREBUILT) $@

citest.ttp: citest.o $(LBR)
	$(CC) $(CFLAGS) $(LDFLAGS) -o$@ citest.o

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false
