# Makefile for libci
# 32-bit Borland C++ (Note: All modules are compiled in C mode)
# To build the library, do:
#       "make -fmakefile.bc32"
#
# -------------------- 32-bit Borland C++ --------------------

### Absolutely necessary for this makefile to work
.AUTODEPEND

## Where zlib.h, zconf.h and zlib.lib are
ZLIB_DIR=..\zlib

## Compiler, linker, librarian and other tools
CC=bcc32
LD=bcc32
LIB=tlib
CP=copy

# -3 = 386, -4 = 486, -5 = Pentium etc.
!ifndef TARGET_CPU
#TARGET_CPU=-6
!endif

# Use this if you don't want Borland's fancy exception handling
# (Caution: doesn't work with CBuilderX)
#NOEHLIB=noeh32.lib

!ifdef DEBUG
CDEBUG=-v
LDEBUG=-v
!else
CDEBUG=
LDEBUG=
!endif

# STACKOFLOW=1
!ifdef STACKOFLOW
CDEBUG=$(CDEBUG) -N
LDEBUG=$(LDEBUG) -N
!endif

# -O2 optimize for speed
# -d  merge duplicate strings
# -k- turn off standard stack frame
# -w  display all warnings
CPPFLAGS=-I$(ZLIB_DIR)
CFLAGS=-O2 -d -k- -w $(TARGET_CPU) $(CDEBUG)

# -M  generate map file
LDFLAGS=-L$(ZLIB_DIR) -M $(LDEBUG)

## Pre-built configuration
# See scripts\cilibconf.mak for more options
!ifndef CILIBCONF_H_PREBUILT
CILIBCONF_H_PREBUILT = scripts\cilibconf.h.prebuilt
!endif

## File lists
OBJS = \
	ci.obj \
	cierror.obj \
	ciget.obj \
	cimem.obj \
	cipread.obj \
	ciread.obj \
	cirio.obj \
	cirtran.obj \
	cirutil.obj \
	ciset.obj \
	citrans.obj \
	ciwio.obj \
	ciwrite.obj \
	ciwtran.obj \
	ciwutil.obj

LIBOBJS = \
	+ci.obj \
	+cierror.obj \
	+ciget.obj \
	+cimem.obj \
	+cipread.obj \
	+ciread.obj \
	+cirio.obj \
	+cirtran.obj \
	+cirutil.obj \
	+ciset.obj \
	+citrans.obj \
	+ciwio.obj \
	+ciwrite.obj \
	+ciwtran.obj \
	+ciwutil.obj

LIBNAME=libci.lib

## Implicit rules
# Braces let make "batch" calls to the compiler,
# 2 calls instead of 12; space is important.
.c.obj:
	$(CC) $(CPPFLAGS) $(CFLAGS) -c {$*.c }

.c.exe:
	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) $*.c \
	  $(LIBNAME) zlib.lib $(NOEHLIB)

.obj.exe:
	$(LD) $(LDFLAGS) $*.obj $(LIBNAME) zlib.lib $(NOEHLIB)

## Major targets
all: libci citest

libci: $(LIBNAME)

citest: citest.exe

test: citest.exe
	citest

## Minor Targets

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	$(CP) $(CILIBCONF_H_PREBUILT) $@

ci.obj:      ci.c      ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cierror.obj: cierror.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciget.obj:   ciget.c   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cimem.obj:   cimem.c   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cipread.obj: cipread.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciread.obj:  ciread.c  ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirio.obj:   cirio.c   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirtran.obj: cirtran.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirutil.obj: cirutil.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciset.obj:   ciset.c   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
citrans.obj: citrans.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwio.obj:   ciwio.c   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwrite.obj: ciwrite.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwtran.obj: ciwtran.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwutil.obj: ciwutil.c ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
citest.obj:  citest.c  ci.h ciconf.h cilibconf.h

$(LIBNAME): $(OBJS)
	-del $(LIBNAME)
	$(LIB) $(LIBNAME) @&&|
$(LIBOBJS), libci
|

# Cleanup
clean:
	-del cilibconf.h
	-del *.obj
	-del $(LIBNAME)
	-del citest.exe
	-del *.lst
	-del *.map
	-del *.tds
	-del ciout.ci

# End of makefile for libci
