# makefile for libci on DEC Alpha Unix
# Copyright (C) 2020-2025 Cosmin Truta
# Copyright (C) 2000-2002, 2006, 2010-2014 Glenn Randers-Pehrson
# Copyright (C) 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

# Library name:
LIBNAME=libci16
CIMAJ=16

# Shared library names:
LIBSO=$(LIBNAME).so
LIBSOMAJ=$(LIBNAME).so.$(CIMAJ)

# Utilities:
CC=cc
AR=ar
RANLIB=ranlib
LN_SF=ln -f -s
CP=cp
RM_F=/bin/rm -f

# Where the zlib library and include files are located
#ZLIBLIB=/usr/local/lib
#ZLIBINC=/usr/local/include
ZLIBLIB=../zlib
ZLIBINC=../zlib

CPPFLAGS=-I$(ZLIBINC) # -DCI_DEBUG=5
CFLAGS=-std -w1 -O
ARFLAGS=rc
LDFLAGS=-L$(ZLIBLIB) -rpath $(ZLIBLIB) libci.a -lz -lm

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts/cilibconf.h.prebuilt

OBJS = ci.o cierror.o ciget.o cimem.o cipread.o \
       ciread.o cirio.o cirtran.o cirutil.o ciset.o \
       citrans.o ciwio.o ciwrite.o ciwtran.o ciwutil.o

.c.o:
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o $@ $*.c

all: $(LIBSO) libci.a citest

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	$(CP) $(CILIBCONF_H_PREBUILT) $@

libci.a: $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)
	$(RANLIB) $@

$(LIBSO): $(LIBSOMAJ)
	$(LN_SF) $(LIBSOMAJ) $(LIBSO)

$(LIBSOMAJ): $(OBJS)
	$(CC) -shared -o $@ $(OBJS) -L$(ZLIBLIB) -soname $(LIBSOMAJ)

citest: citest.o libci.a
	$(CC) -o citest $(CFLAGS) citest.o $(LDFLAGS)

test: citest
	./citest

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false

install-static:
	@echo "The $@ target is no longer supported by this makefile."
	@false

install-shared:
	@echo "The $@ target is no longer supported by this makefile."
	@false

clean:
	$(RM_F) *.o libci.a citest ciout.ci
	$(RM_F) $(LIBSO) $(LIBSOMAJ)* cilibconf.h

# DO NOT DELETE THIS LINE -- make depend depends on it.

ci.o:      ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cierror.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciget.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cimem.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cipread.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciread.o:  ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciset.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
citrans.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwrite.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h

citest.o:  ci.h ciconf.h cilibconf.h
