# makefile for libci using emscripten
# Copyright (C) 2000, 2014, 2019-2025 Cosmin Truta
# Copyright (C) 2021 Kirk Roerig
# Copyright (C) 2008, 2014 Glenn Randers-Pehrson
# Copyright (C) 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

# Location of the zlib library and include files
ZLIBINC = ../zlib
ZLIBLIB = ../zlib

# Compiler, linker, lib and other tools
CC = emcc
LD = $(CC)
AR = emar
RANLIB = emranlib
CP = cp
RM_F = rm -f

STDC = -pedantic-errors # -std=c99
WARN = -Wall -Wextra -Wundef
WARNMORE = -Wcast-align -Wconversion -Wshadow -Wpointer-arith -Wwrite-strings \
           -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes
LOCAL_CPPFLAGS =
CPPFLAGS = -I$(ZLIBINC) # -DCI_DEBUG=5
ALL_CPPFLAGS = $(LOCAL_CPPFLAGS) $(CPPFLAGS)
LOCAL_CFLAGS = $(STDC) $(WARN) # $(WARNMORE)
CFLAGS = -O2
ALL_CFLAGS = $(LOCAL_CFLAGS) $(CFLAGS)
ARFLAGS = rc
LDFLAGS = -L$(ZLIBLIB)
CITEST_LDFLAGS = --preload-file=citest.ci
LIBS = -lz -lm

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts/cilibconf.h.prebuilt

# File lists
OBJS = ci.o cierror.o ciget.o cimem.o cipread.o \
       ciread.o cirio.o cirtran.o cirutil.o ciset.o \
       citrans.o ciwio.o ciwrite.o ciwtran.o ciwutil.o

# Targets
all: static

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	$(CP) $(CILIBCONF_H_PREBUILT) $@

.c.o:
	$(CC) -c $(ALL_CPPFLAGS) $(ALL_CFLAGS) -o $@ $*.c

static: libci.a citest

shared:
	@echo This makefile cannot create shared libraries.
	@false

libci.a: $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)
	$(RANLIB) $@

test: citest
	node ./citest

citest: citest.o libci.a
	$(LD) $(LDFLAGS) $(CITEST_LDFLAGS) -o $@ citest.o libci.a $(LIBS)

clean:
	$(RM_F) *.o libci.a citest ciout.ci cilibconf.h
	$(RM_F) citest.data citest.wasm

ci.o:      ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cierror.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciget.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cimem.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cipread.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciread.o:  ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
cirutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciset.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
citrans.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwio.o:   ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwrite.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwtran.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
ciwutil.o: ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h

citest.o:  ci.h ciconf.h cilibconf.h
