# makefile for libci on win-arm64
# Copyright (C) 2021 Gabor Kertesz
# Copyright (C) 1998 Tim Wegner
# Copyright (C) 2006,2009,2011,2014 Glenn Randers-Pehrson
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h
#
# Assumes that zlib.lib, zconf.h, and zlib.h have been copied to ..\zlib
# To use, do "nmake /f scripts\makefile.vcwin-arm64"

# -------- Microsoft Visual C++ 2.0 and later --------

# Compiler, linker, librarian and other tools
CC = cl
LD = link
AR = lib
CPPFLAGS = -I..\zlib
CFLAGS  = -nologo -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -DCI_ARM_NEON_OPT=1 -MD -O2 -W3
LDFLAGS = -nologo
ARFLAGS = -nologo
CP = copy
RM = del

# Uncomment next to put error messages in a file
#ERRFILE= >> cierrs.log

# Pre-built configuration
# See scripts\cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts\cilibconf.h.prebuilt

# File extensions
O = .obj

# File lists
OBJS1 = ci$(O) cierror$(O) ciget$(O) cimem$(O) cipread$(O)
OBJS2 = ciread$(O) cirio$(O) cirtran$(O) cirutil$(O) ciset$(O)
OBJS3 = citrans$(O) ciwio$(O) ciwrite$(O) ciwtran$(O) ciwutil$(O)
OBJS4 = arm_init$(O) filter_neon_intrinsics$(O) palette_neon_intrinsics$(O)
OBJS  = $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4)

# Targets
all: libci.lib

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	$(CP) $(CILIBCONF_H_PREBUILT) $@

ci$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cierror$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciget$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cimem$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cipread$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciread$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirio$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirtran$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirutil$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciset$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

citrans$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwio$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwrite$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwtran$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwutil$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

arm_init$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) arm\$*.c $(ERRFILE)

filter_neon_intrinsics$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) arm\$*.c $(ERRFILE)

palette_neon_intrinsics$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) arm\$*.c $(ERRFILE)

libci.lib: $(OBJS)
	-$(RM) $@
	$(AR) $(ARFLAGS) -out:$@ $(OBJS) $(ERRFILE)

citest.exe: citest$(O) libci.lib
	$(LD) $(LDFLAGS) -out:$@ citest$(O) libci.lib ..\zlib\zlib.lib $(ERRFILE)

citest$(O): ci.h ciconf.h cilibconf.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

test: citest.exe
	citest.exe

clean:
	-$(RM) *$(O)
	-$(RM) libci.lib
	-$(RM) cilibconf.h
	-$(RM) citest.exe
	-$(RM) ciout.ci

# End of makefile for libci
