# Makefile for libci
# Microsoft Visual C++ with Intel C/C++ Compiler 4.0 and later

# Copyright (C) 2006, 2014 Glenn Randers-Pehrson
# Copyright (C) 2000, Pawel Mrochen, based on makefile.msc which is
# copyright 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h
#
# To use, do "nmake /f scripts\makefile.intel"
#
# ------------------- Intel C/C++ Compiler 4.0 and later -------------------

# Where the zlib library and include files are located
ZLIBLIB=..\zlib
ZLIBINC=..\zlib

# Target CPU
CPU=6		# Pentium II
#CPU=5		# Pentium

# Calling convention
CALLING=r	# __fastcall
#CALLING=z	# __stdcall
#CALLING=d	# __cdecl

# Uncomment next to put error messages in a file
#ERRFILE=>>cierrs

# --------------------------------------------------------------------------

CC=icl
CPPFLAGS=-I$(ZLIBINC)
CFLAGS=-O2 -G$(CPU)$(CALLING) -Qip -Qunroll4 -nologo
LD=link
LDFLAGS=/SUBSYSTEM:CONSOLE /NOLOGO
CP=cp

# Pre-built configuration
# See scripts\cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts\cilibconf.h.prebuilt

# File extensions
O=.obj

# File lists
OBJS1=ci$(O) cierror$(O) ciget$(O) cimem$(O) cipread$(O)
OBJS2=ciread$(O) cirio$(O) cirtran$(O) cirutil$(O) ciset$(O)
OBJS3=citrans$(O) ciwio$(O) ciwrite$(O) ciwtran$(O) ciwutil$(O)
OBJS=$(OBJS1) $(OBJS2) $(OBJS3)

# Targets
all: test

cilibconf.h: $(CILIBCONF_H_PREBUILT)
	$(CP) $(CILIBCONF_H_PREBUILT) $@

ci$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cierror$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciget$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cimem$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cipread$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciread$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirio$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirtran$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

cirutil$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciset$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

citrans$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwio$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwrite$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwtran$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

ciwutil$(O): ci.h ciconf.h cilibconf.h cipriv.h cistruct.h ciinfo.h cidebug.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

libci.lib: $(OBJS)
	if exist libci.lib del libci.lib
	lib /NOLOGO /OUT:libci.lib $(OBJS)

citest.exe: citest.obj libci.lib
	$(LD) $(LDFLAGS) /OUT:citest.exe citest.obj libci.lib $(ZLIBLIB)\zlib.lib

citest$(O): ci.h ciconf.h cilibconf.h
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $*.c $(ERRFILE)

test: citest.exe
	citest.exe

# End of makefile for libci
