# Commodore Amiga Makefile
# makefile for libci and SAS C V6.5x compiler
# Copyright (C) 1995-2000 Wolf Faust
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h
#
# Location/path of zlib include files
ZLIB=/zlib
#compiler
CC=sc
#compiler flags
# WARNING: a bug in V6.51 causes bad code with OPTGO
#          So use V6.55 or set NOOPTGO!!!!!!!!!
CFLAGS= NOSTKCHK PARMS=REG OPTIMIZE OPTGO OPTPEEP OPTINLOCAL OPTINL\
	OPTLOOP OPTRDEP=4 OPTDEP=4 OPTCOMP=4 INCLUDEDIR=$(ZLIB) \
	DEFINE=CI_INTERNAL
#linker flags
LDFLAGS= SD ND BATCH
#link libs
LDLIBS= libci.lib libgz.lib LIB:scm.lib LIB:sc.lib Lib:amiga.lib
# linker
LN= slink
# file deletion command
RM= delete quiet
# library (.lib) file creation command
AR= oml

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT = scripts/cilibconf.h.prebuilt

OBJS = ci.o cierror.o ciget.o cimem.o cipread.o \
       ciread.o cirio.o cirtran.o cirutil.o ciset.o \
       citrans.o ciwio.o ciwrite.o ciwtran.o ciwutil.o

all: libci.lib citest

libci.lib: $(OBJS)
-$(RM) libci.lib
$(AR) libci.lib r $(OBJS)

$(OBJS): cipriv.h ci.h ciconf.h cilibconf.h ciinfo.h cistruct.h cidebug.h

cilibconf.h: $(CILIBCONF_H_PREBUILT)
COPY $(CILIBCONF_H_PREBUILT) TO cilibconf.h

citest: citest.o libci.lib
$(LN) <WITH <
$(LDFLAGS)
TO citest
FROM LIB:c.o citest.o
LIB $(LDLIBS)
<

