# makefile for libci
# Copyright (C) 2018-2025 Cosmin Truta
# Copyright (C) 2007-2009, 2014 Glenn Randers-Pehrson
# Copyright (C) 1995 Guy Eric Schalnat, Group 42, Inc.
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

SHLIB_MAJOR=	16
SHLIB_MINOR=	0

LIB=	ci
SRCS=	ci.c cierror.c ciget.c cimem.c cipread.c \
	ciread.c cirio.c cirtran.c cirutil.c ciset.c \
	citrans.c ciwio.c ciwrite.c ciwtran.c ciwutil.c
HDRS=	ci.h ciconf.h cilibconf.h

CPPFLAGS+=	-I${.CURDIR}
CFLAGS+=	-Wall -Wextra -Wundef

CLEANFILES+=	citest.o citest cilibconf.h

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT= scripts/cilibconf.h.prebuilt

.c.o:
	${CC} -c ${CPPFLAGS} ${CFLAGS} -o $@ $*.c

cilibconf.h:	${CILIBCONF_H_PREBUILT}
	cp ${CILIBCONF_H_PREBUILT} $@

citest.o:	citest.c
	${CC} -c ${CPPFLAGS} ${CFLAGS} ${.ALLSRC} -o ${.TARGET}

citest:	citest.o
	${CC} ${LDFLAGS} ${.ALLSRC} -o ${.TARGET} -L${.OBJDIR} -lci -lz -lm

test:	citest
	env LD_LIBRARY_PATH="${.OBJDIR}" ./citest

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false

.include <bsd.lib.mk>
