# makefile for libci under FreeBSD
# Copyright (C) 2018-2025 Cosmin Truta
# Copyright (C) 2014 Glenn Randers-Pehrson and Andrey A. Chernov
# Copyright (C) 2002, 2007, 2009 Glenn Randers-Pehrson and Andrey A. Chernov
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

LIB=		ci
SHLIB_VER=	16
SHLIB_MAJOR=	${SHLIB_VER}
SHLIB_MINOR=	0

ZLIBLIB=	/usr/lib
ZLIBINC=	/usr/include

LDADD+=		-lm -lz
#LDADD+=	-lm -lz -lssp_nonshared   # for OSVERSION < 800000 ?

DPADD+=		${LIBM} ${LIBZ}

CPPFLAGS+=	-I. -I${ZLIBINC}
CFLAGS+=	-Wall -Wextra -Wundef
LDFLAGS+=	-L. -L${ZLIBLIB}

CLEANFILES+=	citest citest.o ciout.ci

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT= scripts/cilibconf.h.prebuilt

SRCS=	ci.c cierror.c ciget.c cimem.c cipread.c \
	ciread.c cirio.c cirtran.c cirutil.c ciset.c \
	citrans.c ciwio.c ciwrite.c ciwtran.c ciwutil.c

.c.o:
	${CC} -c ${CPPFLAGS} ${CFLAGS} -o $@ $*.c

cilibconf.h:	${CILIBCONF_H_PREBUILT}
	cp ${CILIBCONF_H_PREBUILT} $@

citest:	citest.o libci.a
	${CC} ${LDFLAGS} -static -o citest citest.o -lci ${LDADD}

test:	citest
	./citest

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false

.include <bsd.lib.mk>
