# makefile for libci on NetBSD
# Copyright (C) 2018-2025 Cosmin Truta
# Copyright (C) 2007-2009, 2014 Glenn Randers-Pehrson
# Copyright (C) 2002 Patrick R.L. Welche
#
# This code is released under the libci license.
# For conditions of distribution and use, see the disclaimer
# and license in ci.h

SHLIB_MAJOR=	16
SHLIB_MINOR=	0

LIB=	ci
SRCS=	ci.c cierror.c ciget.c cimem.c cipread.c \
	ciread.c cirio.c cirtran.c cirutil.c ciset.c \
	citrans.c ciwio.c ciwrite.c ciwtran.c ciwutil.c
INCS=	ci.h ciconf.h cilibconf.h

CPPFLAGS+=	-I${.CURDIR}
CFLAGS+=	-Wall -Wextra -Wundef

CLEANFILES+=	citest.o citest cilibconf.h

# Pre-built configuration
# See scripts/cilibconf.mak for more options
CILIBCONF_H_PREBUILT= scripts/cilibconf.h.prebuilt

# We should be able to do something like this instead of the manual
# uncommenting, but it core dumps for me at the moment:
# .if ${MACHINE_ARCH} == "i386"
#   MKLINT= no
# .endif

.c.o:
	${CC} -c ${CPPFLAGS} ${CFLAGS} -o $@ $*.c

cilibconf.h:	${CILIBCONF_H_PREBUILT}
	cp ${CILIBCONF_H_PREBUILT} $@

citest.o:	citest.c
	${CC} -c ${CPPFLAGS} ${CFLAGS} ${.ALLSRC} -o ${.TARGET}

citest:	citest.o libci.a
	${CC} ${LDFLAGS} ${.ALLSRC} -o ${.TARGET} -lz -lm

test:	citest
	./citest

install:
	@echo "The $@ target is no longer supported by this makefile."
	@false

.include <bsd.lib.mk>
